cartoview/catalog/csw_catalog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^csw$','cartoview2.catalog.csw_catalog.views.csw'),
)

cartoview/catalog/urls.py
import os

from django.conf.urls import patterns, url , include


urlpatterns = patterns('',
    url(r'^$', 'cartoview2.catalog.views.home', name='catalog_base_url'),
    (r'^results/$', 'cartoview2.catalog.views.results'),
    (r'^tag/(?P<tag_id>\d+)/$', 'cartoview2.catalog.views.tag_results'),
    url (r'^resources/user/(?P<user_id>\d+)/$', 'cartoview2.catalog.views.user_results' , name = 'user_resources'),
    (r'^category/(?P<category_id>\d+)/$', 'cartoview2.catalog.views.category_results'),
    (r'^search/$', 'cartoview2.catalog.views.search_results'),
    url(r'^resource/(?P<resource_id>\d+)/$', 'cartoview2.catalog.views.resource_details', name='resource_details'),
    (r'^resource/delete/(?P<resource_id>\d+)/$', 'cartoview2.catalog.views.resource_delete'),
    (r'^resource/edit/(?P<resource_id>\d+)/$', 'cartoview2.catalog.views.resource_edit'),
    (r'^resource/(?P<resource_id>\d+)/(?P<slug>[-\w]+)/$', 'cartoview2.catalog.views.resource_details'),
    (r'^tags/$', 'cartoview2.catalog.views.get_tag_list'),
    (r'^apps/$', 'cartoview2.catalog.views.get_app_list'),
    (r'^comments/', include('django.contrib.comments.urls')),

    (r'^csw_catalog/', include('cartoview2.catalog.csw_catalog.urls')),
    url(r'^submit/', 'cartoview2.catalog.views.submit',name='catalog_submit'),
    url(r'^submit_api/(?P<resource_id>\d+)/$','cartoview2.catalog.views.API_submit', name='catalog.submit_api'),
    url(r'^submit_data/(?P<resource_id>\d+)/$','cartoview2.catalog.views.Data_submit', name='catalog.submit_data'),
    url(r'^submit_app/(?P<resource_id>\d+)/$','cartoview2.catalog.views.App_submit', name='catalog.submit_app'),
    url(r'^settings/', 'cartoview2.catalog.views.settings',name = 'catalog_settings'),
    url(r'^new/', 'cartoview2.catalog.views.create_new', name='create_new'),
    url(r'^validate_url/', 'cartoview2.catalog.views.validate_url', name='validate_url'),
    url(r'^security/permissions/(?P<resource_id>\d+)$',
                           'cartoview2.catalog.security.views.resource_permissions',
                           name='resource_permissions'),
    url(r'^account/ajax_lookup$', 'cartoview2.catalog.security.views.ajax_lookup',
                           name='account_ajax_lookup'),

)

import rest

cartoview/catalog/models.py
import os
from django.contrib.contenttypes.models import ContentType
from django.core.files import File
from lxml import etree
from shapely.wkt import loads

from operator import attrgetter
from django.db import models
from django.db.models import Q
from django.conf import settings
from csw_catalog import settings as csw_settings
from django.contrib.auth.models import User, Permission
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from cartoview2.core import models as core_models
from sorl.thumbnail.fields import ImageField
from djangoratings.fields import RatingField
from django.contrib.gis.db import models
from django.contrib.sites.models import Site
from security.models import *
from django.db.models import signals
class Tag(models.Model):
    tag_name = models.CharField(max_length=150)

    def __unicode__(self):
        return '%s' % self.tag_name

    class Meta:
        ordering = ['tag_name']


class Category(models.Model):
    category_name = models.CharField(max_length=150)

    def __unicode__(self):
        return '%s' % self.category_name

    class Meta:
        ordering = ['category_name']

class DataType(models.Model):
    data_type = models.CharField(max_length=50)

    def __unicode__(self):
        return '%s' % self.data_type

    class Meta:
        ordering = ['data_type']


class UrlType(models.Model):
    url_type = models.CharField(max_length=50)

    def __unicode__(self):
        return '%s' % self.url_type

    class Meta:
        ordering = ['url_type']


class UpdateFrequency(models.Model):
    update_frequency = models.CharField(max_length=50)

    def __unicode__(self):
        return '%s' % self.update_frequency

    class Meta:
        ordering = ['update_frequency']


class CoordSystem(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    EPSG_code = models.IntegerField(blank=True, help_text="Official EPSG code, numbers only")

    def __unicode__(self):
        return '%s, %s' % (self.EPSG_code, self.name)

    class Meta:
        ordering = ['EPSG_code']
        verbose_name = 'Coordinate system'


class Resource(models.Model,PermissionLevelMixin):
    @classmethod
    def search(cls, qs = None, objs = None):
        if objs == None:
            objs = cls.objects.filter(is_published = True)

        if qs:
            objs = objs.filter(Q(name__icontains=qs) | Q(description__icontains=qs) | Q(organization__icontains=qs) | Q(division__icontains=qs) |
                               Q(tags__in=Tag.objects.filter(tag_name__icontains=qs))|Q(categories__in=Category.objects.filter(category_name__icontains=qs)))

        return objs

    def save(self, *args, **kwargs):
        if not self.pk:
            super(Resource, self).save(*args, **kwargs)

        self.csw_xml = self.gen_csw_xml()
        self.csw_anytext = self.gen_csw_anytext()
        super(Resource, self).save(*args, **kwargs)

    # Basic Info
    class Meta:
        permissions = (
            ("view_resource", "Can view resource"),
            )
    app = models.ForeignKey(core_models.App ,null=True,blank=True)
    name = models.CharField(max_length=255)
    short_description = models.CharField(max_length=255,blank=True)
    release_date = models.DateField(blank=True, null=True)
    time_period = models.CharField(max_length=50, blank=True)
    organization = models.CharField(max_length=255, blank=True)
    division = models.CharField(max_length=255, blank=True)
    usage = models.TextField()
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    categories = models.ManyToManyField(Category, blank=True, null=True)
    data_types = models.ManyToManyField(DataType, blank=True, null=True)

    # More Info
    description = models.TextField()
    contact_phone = models.CharField(max_length=50, blank=True)
    contact_email = models.CharField(max_length=255, blank=True)
    contact_url = models.CharField(max_length=255, blank=True)

    updates = models.ForeignKey(UpdateFrequency, null=True, blank=True)
    area_of_interest = models.CharField(max_length=255, blank=True)
    is_published = models.BooleanField(default=True, verbose_name="Public")
    location_extent = models.PolygonField('Extent', srid = 4326, null = True, blank = True)
    created_by = models.ForeignKey(User, related_name='created_by')
    last_updated_by = models.ForeignKey(User, related_name='updated_by')
    created = models.DateTimeField(auto_now=True)
    last_updated = models.DateTimeField(auto_now=True)
    metadata_contact = models.CharField(max_length=255, blank=True)
    metadata_notes = models.TextField(blank=True)
    coord_sys = models.ManyToManyField(CoordSystem, blank=True, null=True,  verbose_name="Coordinate system")

    rating = RatingField(range=5, can_change_vote=True)

    update_frequency = models.CharField(max_length=255, blank=True)
    data_formats = models.CharField(max_length=255, blank=True)
    proj_coord_sys = models.CharField(max_length=255, blank=True, verbose_name="Coordinate system")

    is_featured = models.BooleanField(default=False,null=False,blank=False)
    # CSW specific properties
    wkt_geometry = models.TextField(blank=True)
    csw_typename = models.CharField(max_length=200,default="csw:Record")
    csw_schema = models.CharField(max_length=200,default="http://www.opengis.net/cat/csw/2.0.2")
    csw_mdsource = models.CharField(max_length=100,default="local")
    csw_xml = models.TextField(blank=True)
    csw_anytext = models.TextField(blank=True)
    objects = models.GeoManager()

    def get_distinct_url_types(self):
        types = []
        for url in self.url_set.all():
            if url.url_type not in types:
                types.append(url.url_type)
        return sorted(types, key=attrgetter('url_type'))

    def get_grouped_urls(self):
        urls = {}
        for utype in UrlType.objects.all():
            urls[utype.url_type] = self.url_set.filter(url_type=utype)
        return urls

    def get_first_image(self):
        images = UrlImage.objects.filter(url__resource=self)
        if images.count() == 0:
            return None
        return images[0]
    def get_last_image(self):
        images = UrlImage.objects.filter(url__resource=self)
        if images.count() == 0:
            return None
        return images.reverse()[0]

    def get_images(self):
        images = UrlImage.objects.filter(url__resource=self)
        if images.count() == 0:
            return None
        return images

    def get_absolute_url(self):
        slug = slugify(self.name)
        return "/resource/%i/%s" % (self.id, slug)

    def __unicode__(self):
        return '%s' % self.name

    # CSW specific properties
    @property
    def csw_identifier(self):
        if not csw_settings.SITEHOST:
            raise RuntimeError('csw_settings.SITEHOST is not set')
        fqrhn = '.'.join((reversed(csw_settings.SITEHOST.split('.'))))
        return 'urn:x-odc:resource:%s::%d' % (fqrhn, self.id)

    @property
    def csw_type(self):
        data_types = self.data_types.values()
        if len(data_types) > 0:
            return data_types[0]['data_type']
        return None

    @property
    def csw_crs(self):
        crs = self.coord_sys.values()
        if len(crs) > 0:
            return crs[0]['name']
        return None

    @property
    def csw_links(self):
        links = []
        for url in self.url_set.all():
            tmp = '%s,%s,%s,%s' % (url.url_label, url.url_type.url_type, 'WWW:DOWNLOAD-1.0-http--download', url.url)
            links.append(tmp)
        abs_url = '%s%s' % (gen_website_url(), self.get_absolute_url())
        link = '%s,%s,%s,%s' % (self.name, self.name, 'WWW:LINK-1.0-http--link', abs_url)
        links.append(link)
        return '^'.join(links)

    @property
    def csw_keywords(self):
        keywords = []
        for keyword in self.tags.values():
            keywords.append(keyword['tag_name'])
        return ','.join(keywords)

    @property
    def csw_creator(self):
        creator = User.objects.filter(username=self.created_by)[0]
        return '%s %s' % (creator.first_name, creator.last_name)

    def gen_csw_xml(self):

        def nspath(ns, element):
            return '{%s}%s' % (ns, element)

        nsmap = {
            'csw': 'http://www.opengis.net/cat/csw/2.0.2',
            'dc' : 'http://purl.org/dc/elements/1.1/',
            'dct': 'http://purl.org/dc/terms/',
            'ows': 'http://www.opengis.net/ows',
            'xsi': 'http://www.w3.org/2001/XMLSchema-instance',
        }

        record = etree.Element(nspath(nsmap['csw'], 'Record'), nsmap=nsmap)
        etree.SubElement(record, nspath(nsmap['dc'], 'identifier')).text = self.csw_identifier
        etree.SubElement(record, nspath(nsmap['dc'], 'title')).text = self.name

        if self.csw_type is not None:
            etree.SubElement(record, nspath(nsmap['dc'], 'type')).text = self.csw_type

        for tag in self.tags.all():
            etree.SubElement(record, nspath(nsmap['dc'], 'subject')).text = tag.tag_name

        etree.SubElement(record, nspath(nsmap['dc'], 'format')).text = str(self.data_formats)

        abs_url = '%s%s' % (gen_website_url(), self.get_absolute_url())
        etree.SubElement(record, nspath(nsmap['dct'], 'references'), scheme='WWW:LINK-1.0-http--link').text = abs_url

        for link in self.url_set.all():
            etree.SubElement(record, nspath(nsmap['dct'], 'references'),
                             scheme='WWW:DOWNLOAD-1.0-http--download').text = link.url

        etree.SubElement(record, nspath(nsmap['dct'], 'modified')).text = str(self.last_updated)
        etree.SubElement(record, nspath(nsmap['dct'], 'abstract')).text = self.description

        etree.SubElement(record, nspath(nsmap['dc'], 'date')).text = str(self.created)
        etree.SubElement(record, nspath(nsmap['dc'], 'creator')).text = str(self.csw_creator)

cartoview/catalog/templates/catalog/app_results.html
{% extends "catalog/app_template.html" %}

{% load thumbnail %}
{% load sorting_tags staticfiles filters%}
{% load pagination_tags %}

{% block title %} Search Results{% endblock %}
{% block styles %}
<style>
.label
 {
right: 0;
top:0;
position:absolute;
border-radius: 6px 0 6px 0;
 }
</style>
{% endblock %}
{% block js_ready %}
	<script>
		$(document).ready(function () {
			//odp.getTags();
			//odp.getCategories();

			//odp.getApps();
			odp.setupSearchInput();

			odp.setupSortLinks();
			//odp.setupFilterLinks();


		});

		function confirm (resourceId){
		    $('<div></div>').appendTo('body')
    .html('<div><h6>Are you sure?</h6></div>')
    .dialog({
        modal: true,
        title: 'Delete Item',
        zIndex: 10000,
        autoOpen: true,
        width: 'auto',
        resizable: false,
        buttons: {
            Yes: function () {
                // $(obj).removeAttr('onclick');
                // $(obj).parents('.Parent').remove();

                window.location = '{% url 'catalog_base_url' %}resource/delete/'+resourceId+'/?next=' + encodeURIComponent('{{current_path}}')

                $(this).dialog("close");
            },
            No: function () {
                $(this).dialog("close");
            }
        },
        close: function (event, ui) {
            $(this).remove();
        }
    });
    }
	</script>
{% endblock %}

            
{% block center_container %}


<div class="row">
	{% if tag %}

        <!--<a href="{{SITE_ROOT}}/ideas" class="resource" id="promotion_header">-->
            <!--<span class="icon_idea"></span> See how data sets are being used, in the <strong>Idea&nbsp;Gallery</strong>.-->
        <!--</a>-->
	    <h1 id="results_label">{{ tag }}</h1>
    {% elif created_user  %}
    <h1 id="results_label">Rescources created by <b>{{created_user.username}}</b></h1>
    {% elif app and app_name %}
        <h1 id="results_label">{{ app_name }}

        </h1>
        {% with app|add:'.new' as new_url_name %}
            {% url new_url_name as new_url %}
                {% if new_url %}
                     <a href="{% url 'cartoview2_base_url' %}{{app}}/new" >Create new</a>
                {% endif %}
        {% endwith %}
	{% else %}
		{% if "search" in current_path and "?" in current_path %}
			<h1 id="results_label">Search Results</h1>
		{% else %}
			<h1 id="results_label">All Records</h1>
		{% endif %}
	{% endif %}
   </div>
	<div id="results_header" class="row">
		<div id="results_info">
		    {% if results.count == 1 %}
			<h2 id="count">{{results.count}} RESULT</h2>
		    {% else %}
			<h2 id="count">{{results.count}} RESULTS</h2>
		    {% endif %}
			<!--<div id="filter">-->
				<!--<ul>-->
                    <!--<li id='filter_all' class="btn-circle"><a href="{% url 'catalog_base_url' %}results/?sort=name&dir=asc" >ALL</a></li>-->
                    <!--<li id='filter_featured' class="btn-circle"><a href="javascript:void()" onClick="odp.getFiltered('featured');return false;">Featured</a></li>-->
					<!--<li id='filter_application' class="btn-circle"><a href="javascript:void()" onClick="odp.getFiltered('application');return false;" >APP</a></li>-->
					<!--<li id='filter_data' class="btn-circle"><a href="javascript:void()" onClick="odp.getFiltered('data');return false;"/>DATA</a></li>-->
					<!--<li id='filter_api' class="btn-circle"><a href="javascript:void()" onClick="odp.getFiltered('api');return false;">API</a></li>-->
					<!--<li class="info_label">FILTER:</li>-->
				<!--</ul>-->
			<!--</div>-->
			<div id="sort">
				<ul>
					<li id="sort_rating_score" class="btn-circle">{% anchor rating_score %}</li>
					<li id="sort_name" class="btn-circle">{% anchor name %}</li>
					<li class="info_label">SORT:</li>
				</ul>
			</div>
		</div>
	</div>
{% autosort results %}
{% autopaginate results settings.resources_per_page %}
	<div id="results_list">
		<ul class="list-group">
    {% if results.count > 0 %}

		{% for r in results %}
			<li class="resource list-group-item row">

               <div class="col-md-3 col-sm-6 col-xs-12 no-col-padding badger-right badger-info">
                {% if r.get_last_image.image %}
                    {% thumbnail r.get_last_image.image "300x200" upscale=True format="PNG" as im %}

						<a  href="{% url 'catalog_base_url' %}resource/{{r.id}}/{{r.name|slugify}}"><img class="img-thumbnail" src="{{ im.url }}" alt="{{r.get_last_image.title}}" >
                     {% endthumbnail%}


                        </a>
                     {% elif r.url_set.all.0.service_type.image %}
                     {% thumbnail r.url_set.all.0.service_type.image  "300x200" upscale=True format="PNG" as im %}

                     <a href="{% url 'catalog_base_url' %}resource/{{r.id}}/{{r.name|slugify}}"><img class='img-thumbnail' src="{{ im.url }}" > </a>
                 {% endthumbnail%}

                       {%elif r.app.app_img%}
                     {% thumbnail r.app.app_img   "300x200"  upscale=True format="PNG"   as im  %}
                     <a href="{% url 'catalog_base_url' %}resource/{{r.id}}/{{r.name|slugify}}"><img class='img-thumbnail' src="{{ im.url }}" > </a>
                            {% endthumbnail %}
					{% else %}

						<a   href="{% url 'catalog_base_url' %}resource/{{r.id}}/{{r.name|slugify}}"><img class='img-thumbnail' src="{%  static 'catalog/images/results_no_image.jpg' %}" alt="No Resource Images"  height="100" width="100"></a>
					{% endif %}
                </div>
               <span class="label label-info tip pull-right">{% firstof r.data_types.all.0.data_type r.url_set.all.0.service_type.service_type r.data r.app.title %}</span>
                <div class="col-md-9">
				<!--<div id="url_types">-->
					<!--{% for u in r.get_distinct_url_types %}-->
						<!--<div class="url_image" id="resource_icon_{{u}}" alt="{{u}}" title="{{u}}"></div>-->
					<!--{% endfor %}</div>-->
                    {% if settings.enable_rating %}
				<div id="rating_image">
					<div id="rating">
						<input name="star_r{{r.id}}" type="radio" class="star star_r{{r.id}}" disabled="disabled"/>
						<input name="star_r{{r.id}}" type="radio" class="star star_r{{r.id}}" disabled="disabled"/>
						<input name="star_r{{r.id}}" type="radio" class="star star_r{{r.id}}" disabled="disabled"/>
						<input name="star_r{{r.id}}" type="radio" class="star star_r{{r.id}}" disabled="disabled"/>
						<input name="star_r{{r.id}}" type="radio" class="star star_r{{r.id}}" disabled="disabled"/>
						<script type="text/javascript">
							var rating = {{r.rating.score|default:"0"}};
							if (rating != 0) {
								$("input:radio.star_r{{r.id}}")[{{r.rating.score}}-1].checked = 'checked';
							}
						</script>
					</div>

				</div>
                    {% endif %}
				<div id="resource_info">
					<h3 id="resource_title"><a href="{% url 'catalog_base_url' %}resource/{{r.id}}/{{r.name|slugify}}">{{r}}</a></h3>

					<h4 id="resource_desc">{{r.short_description|safe|default:"No description available."}}</h4>
					<div id="resource_button">
                    {% for url in r.get_grouped_urls.Application %}
                            {% if url.url_label == 'View' %}
                                 <a class="btn btn-primary" href="{{url.url}}">{{url.url_label}}</a>
                            {% endif %}
                         {% endfor %}
					<a class="btn btn-primary" href="{% url 'catalog_base_url' %}resource/{{r.id}}/{{r.name|slugify}}">Details</a>

                    {% if r.app.name in perms %}
                          {% if r.app.name|can_delete in perms %}
                                <a class="btn  btn-danger" href="javascript:void()" onClick="confirm({{r.id}});return false;">Delete</a>
                    {% endif %}

                    {% elif r.get_grouped_urls.API or resource.get_grouped_urls.Data  %}
                        {% if perms.catalog.delete_resource %}
                   <a class="btn btn-danger" href="javascript:void()" onClick="confirm({{r.id}});return false;">Delete</a>
                        {% endif %}
                    {% endif %}
				</div>
            </div>
			</li>
		{% endfor %}
    {% else %}
      <li class="resource list-group-item">
        <div class="resource error_message">
      Did your search return zero results? Try limiting or expanding your search terms.</div>

      </li>
    {% endif %}

		</ul>
	</div>

	<div id="pager">{% paginate %}</div>

{% endblock %}

cartoview/catalog/templates/catalog/app_template.html
{% extends "catalog/base.html" %}

{% block js_ready %}
	<script>
		$(document).ready(function () {
			odp.getTags();
			odp.getCategories();

			//odp.getApps();
			odp.setupSearchInput();
		});
	</script>
{% endblock %}

          {% block top-bar%}
    {% include "catalog/searchbar.html" %}
        {% endblock top-bar %}

{% block content %}




      <div id="center_container" class="home col-md-10 ">


		<div id="center_content">
			{% block center_container %}
			{% endblock %}
		</div>

	</div>


  {% include "catalog/footer.html" %}

{% block extra_script %}{% endblock extra_script %}
{% endblock %}

cartoview/catalog/templates/catalog/loginlogout.html
      <div id="account">
				<div id="account_text" class="small_dark"></div>
				{% if user.is_authenticated %}
					<a href="{% url 'cartoview2_base_url' %}/accounts/logout/?next=/">Logout</a>
				{% else %}
          <a href="{% url 'cartoview2_base_url' %}accounts/signup/">Signup</a> or
					<a href="{% url 'account_login' %}?next={{ request.get_full_path }}">Login</a>
				{% endif %}
			</div>

cartoview/catalog/templates/catalog/new_app.html
{% extends "catalog/template-submit.html" %}
{% load thumbnail filters %}
{% load sorting_tags %}
{% load pagination_tags %}
{% load staticfiles %}
{% block title %}{{settings.title}}{% endblock %}
{% block styles %}

<style>
.label
 {
right: 0;
    top:0;
position:absolute;
border-radius: 6px 0 6px 0;
 }
</style>
{% endblock %}
{% block js_ready %}
	<script>
		$(document).ready(function () {
			odp.getTags();
			odp.getCategories();

			//odp.getApps();
			odp.setupSearchInput();
			odp.setupSortLinks();
			odp.setupFilterLinks();
		});

		function confirm (resourceId){
		    $('<div></div>').appendTo('body')
    .html('<div><h6>Are you sure?</h6></div>')
    .dialog({
        modal: true,
        title: 'Delete Item',
        zIndex: 10000,
        autoOpen: true,
        width: 'auto',
        resizable: false,
        buttons: {
            Yes: function () {
                // $(obj).removeAttr('onclick');
                // $(obj).parents('.Parent').remove();

                window.location = '{% url 'catalog_base_url' %}resource/delete/'+resourceId

                $(this).dialog("close");
            },
            No: function () {
                $(this).dialog("close");
            }
        },
        close: function (event, ui) {
            $(this).remove();
        }
    });
		}
	</script>
{% endblock %}

{% block center_container %}


<!--<h1 id="results_label">Gallery</h1>-->

<a class="btn btn-warning  pull-right" href="{% url 'catalog_base_url' %}" ><span class="glyphicon glyphicon-arrow-left"></span> Back to catalog</a>
        <br><br>
	<div id="results_list" class="row">
		<ul class="list-group">
            <!------------------------------------------------------------------------>
 {% if user.is_authenticated %}

    {% if user.username|has_add  or perms.catalog.add_resource %}

        {% if perms.catalog.add_resource %}
            <li class="resource list-group-item row">
                 <div class="col-md-3 col-sm-6 col-xs-12 no-col-padding badger-right badger-info">


						<a   href="{% url 'catalog_base_url' %}submit"><img class='img-thumbnail' src="{% static 'catalog/images/submit.jpg'%}" alt="No Resource Images" ></a>

                </div>
                <div class="col-md-9">

				<div id="submit_info">

					<h3 id="Submit_title"><a href="{% url 'catalog_base_url' %}submit/">Submit resource</a></h3>

					<h4 id="submit_desc">You can submit data sources , services , web apps and even documents into the catalog to be consumed through other cartoview apps or even served as CSW.</h4><br>

            </div>
                    </div>
                 <div id="submit_button" style="width: 100%;float: left;">

					<a class="btn btn-primary btn-danger pull-right" href="{% url 'catalog_base_url' %}submit/">Submit <span class ='glyphicon glyphicon-file'></span></a>
				</div>
			</li>
            <li><hr></li>
            {% endif  %}
            <!-------------------------------------------------------------------------------->
    {% if CARTOVIEW_APPS.count > 0 %}

		{% for app in CARTOVIEW_APPS %}
            {% if app.in_menu %}
                {% if app.name|can_add in perms or app.name|has_no_perms %}
			<li class="resource list-group-item row">
                 <div class="col-md-3 col-sm-6 col-xs-12 no-col-padding badger-right badger-info">

                {% if app.app_img %}

{% thumbnail app.app_img  '300x200'   as im %}
						<a  href="{% url 'cartoview2_base_url' %}{{app.name}}/new/"><img class="img-thumbnail" src="{{ im.url }}" alt="{{app.title}}" >
                        </a>
                            {% endthumbnail  %}


					{% else %}
						<a   href="{% url 'catalog_base_url' %}resource/{{r.id}}/{{r.name|slugify}}"><img class='img-thumbnail' src="{% static 'catalog/images/results_no_image.jpg'%}" alt="No Resource Images" ></a>
					{% endif %}
                </div>
                <div class="col-md-9">

				<div id="resource_info">
                    {% if   app.new_url %}
					<h3 id="resource_title"><a href="{% url 'cartoview2_base_url' %}{{app.name}}/new/">{{app.title}}</a></h3>
                    {% else %}
					<h3 id="resource_title"><a href="{% url 'cartoview2_base_url' %}{{app.name}}/">{{app.title}}</a></h3>
                    {% endif %}
					<h4 id="resource_desc">{{app.description|safe|default:"No description available."}}</h4>

            </div>
                    </div>
                <div id="resource_button" style="width: 100%;float: left;">

                        {% if   app.new_url %}
					<a class="btn btn-primary pull-right" href="{% url 'cartoview2_base_url' %}{{app.name}}/new/">Create New <span class ='glyphicon glyphicon-file'></span></a>
                        {%else %}
					<a class="btn btn-primary btn-info pull-right" href="{% url 'cartoview2_base_url' %}{{app.name}}/">Go to App <span class ='glyphicon glyphicon-hand-right'></span></a>
                {% endif %}
				</div>
			</li>
            {% endif %}
            {% endif %}
		{% endfor %}
    {% else %}
      <li class="resource list-group-item">
        <div class="resource error_message">
      No items here.</div>

      </li>
    {% endif %}
            {% else %}
            <li class="resource list-group-item">
        <div class="resource error_message">
      Only authorized users are allowed to create new instances.</div>

      </li>

        {% endif %}
    {% else %}
          <li class="resource list-group-item">
        <div class="resource error_message">
      Only authorized users are allowed to create new instances.</div>

      </li>

            {% endif %}
		</ul>
	</div>



{% endblock %}